### ISSUE TITLE
Throws an error with PHP 8

### ISSUE THREAD

**Issue by alexgaertner** [Sebobo/Shel.CriticalCSS#5]
When i try to use this Plugin with PHP 8 Flow throws an error: "join(): Argument #2 ($array) must be of type ?array, string given" 

https://github.com/Sebobo/Shel.CriticalCSS/blob/7d4f274750d17ed1c58027aff8a0b61fbb8ab5c5/Classes/Service/StylesService.php#L62

**Comment by Sebobo** [comment]
Thx!

2.0.2 should fix all those deprecated function issues :)
